import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const Clinical=require('../public/clinical.js');
export async function runCataract({request,check,accounts,su,password,base}) {
  const cases='/api/collections/cases/records',users='/api/collections/users/records',audit='/api/collections/audit_logs/records',targets='/api/collections/kpi_targets/records',actions='/api/collections/quality_actions/records';
  const editor=accounts.editor.token,viewer=accounts.viewer.token,admin=accounts.admin.token;
  const sample={hn:'TEST-001',patient_name:'ผู้ป่วยทดสอบเท่านั้น',surgery_date:'2026-01-01',surgeon:'แพทย์สมมติ',procedure:'Phaco + IOL',eye:'OD',diagnosis:'Cataract',pain_score:'0'};
  check((await request(cases,'GET',undefined,admin)).data.totalItems===0,'new database starts empty');
  check(Clinical.kpis([]).every(k=>k.value===null&&k.denominator===0),'empty KPI is N/A');
  check((await request(cases)).data.items.length===0,'guest list empty');
  check((await request(cases,'POST',sample)).status>=400,'guest create blocked');
  check((await request(cases,'POST',sample,viewer)).status>=400,'viewer create blocked');
  const created=await request(cases,'POST',sample,editor);
  check(created.status===200,`editor create case: ${JSON.stringify(created)}`);
  const id=created.data.id;
  check(created.data.created_by===accounts.editor.record.id && created.data.revision===1,'server stamps actor and revision');
  check((await request(`${cases}/${id}`)).status===404,'guest detail blocked');
  for(const [role,token] of [['viewer',viewer],['editor',editor],['admin',admin]]){
    const result=await request(`${cases}/${id}`,'GET',undefined,token);check(result.status===200,`${role} reads case`);
    if(role==='viewer')check(result.data.patient_name==='ปกปิดชื่อผู้ป่วย'&&!result.data.hn.includes('TEST')&&!Object.hasOwn(result.data,'notes'),'viewer API masks identifiers');
  }
  for(const [method,body] of [['PATCH',{surgeon:'changed',revision:1}],['DELETE',undefined]])check((await request(`${cases}/${id}`,method,body,viewer)).status>=400,`viewer ${method} denied`);
  check((await request(`${cases}/${id}`,'DELETE',undefined,editor)).status>=400,'editor delete denied');
  check((await request(`${cases}/${id}`,'DELETE',undefined,admin)).status>=400,'hard delete denied; admin archive instead');
  check((await request(cases,'POST',sample,editor)).status===400,'duplicate HN date eye rejected');
  check((await request(cases,'POST',{...sample,hn:'test-001'},editor)).status===400,'HN case normalization prevents duplicate');
  check((await request(cases,'POST',{...sample,hn:'TAMPER',unknown_field:true},editor)).status===400,'unknown case fields rejected');
  check((await request(`${cases}/${id}`,'PATCH',{revision:1,'created_by+':'forged'},editor)).status===400,'metadata modifiers rejected');
  check((await request('/api/collections/items/records','GET',undefined,admin)).status===403,'legacy item API retired');
  const invalids=[{surgery_date:'2026-02-30'},{surgery_date:'2099-01-01'},{hn:'  '},{hn:'<img>'},{patient_name:'   '},{eye:'X'},{pain_score:'11'},{pain_score:'NaN'},{pain_score:'-1'},{pain_score:'1.5'},{surgery_time:'25:99'},{day1_date:'2026-01-02'},{day1_va:'6/6'},{day1_date:'2025-12-31',day1_va:'6/6'},{day1_date:'2026-01-09',day1_va:'6/6',week1_date:'2026-01-08',week1_va:'6/6'},{va_outcome:'pass'},{endophthalmitis:'maybe'},{created_by:'forged'},{updated_by:'forged'},{archived:true}];
  for(const override of invalids)check((await request(cases,'POST',{...sample,hn:'INVALID',...override},editor)).status>=400,`invalid case rejected ${JSON.stringify(override)}`);
  const full={day1_date:'2026-01-02',day1_va:'6/12',week1_date:'2026-01-08',week1_va:'6/9',month1_date:'2026-02-01',month1_va:'6/6',va_outcome:'pass',endophthalmitis:'no',wound_leak:'no',reoperation:'no',biometry:'pass',refractive:'pass',revision:1};
  const saved=await request(`${cases}/${id}`,'PATCH',full,editor);check(saved.status===200,`follow-up saved: ${JSON.stringify(saved)}`);
  check(saved.data.revision===2 && saved.data.month1_va==='6/6','save persists with incremented revision');
  check((await request(`${cases}/${id}`,'PATCH',{revision:1,notes:'stale'},editor)).status===409,'stale update rejected');
  check((await request(`${cases}/${id}`,'PATCH',{notes:'missing revision'},editor)).status===409,'missing revision rejected');
  check((await request(`${cases}/${id}`,'PATCH',{revision:2,archived:true},editor)).status===403,'editor archive denied');
  const races=await Promise.all([request(`${cases}/${id}`,'PATCH',{revision:2,notes:'race A'},editor),request(`${cases}/${id}`,'PATCH',{revision:2,notes:'race B'},editor)]);
  check(races.filter(r=>r.status===200).length===1 && races.filter(r=>r.status===409).length===1,'concurrent updates have one winner');
  const logs=await request(`${audit}?filter=${encodeURIComponent(`record_id = "${id}"`)}`,'GET',undefined,admin);
  check(logs.data.totalItems===3,`exactly one audit per successful write: ${JSON.stringify(logs)}`);
  check(!JSON.stringify(logs.data).includes(sample.patient_name)&&!JSON.stringify(logs.data).includes(sample.hn),'audit omits patient identifiers');
  check((await request(audit,'GET',undefined,viewer)).data.totalItems===0,'viewer audit denied');
  check((await request(audit,'POST',{entity:'cases',record_id:id,actor:'fake',operation:'create'},admin)).status>=400,'audit injection denied');
  check((await request(`${audit}/${logs.data.items[0].id}`,'DELETE',undefined,admin)).status>=400,'audit deletion denied');
  const defs=await request(targets,'GET',undefined,viewer);check(defs.data.items.length===6 && defs.data.items.every(t=>!t.enabled),'targets seeded as unconfigured metadata');
  const va=defs.data.items.find(t=>t.key==='va_outcome');
  check((await request(`${targets}/${va.id}`,'PATCH',{enabled:true,target:90},editor)).status>=400,'editor cannot configure targets');
  check((await request(`${targets}/${va.id}`,'PATCH',{target:101},admin)).status===400,'invalid target rejected');
  check((await request(`${targets}/${va.id}`,'PATCH',{key:'changed'},admin)).status===400,'KPI definition protected');
  check((await request(`${targets}/${va.id}`,'PATCH',{min_sample:0},admin)).status===400,'minimum sample must be positive');
  check((await request(`${targets}/${va.id}`,'PATCH',{enabled:true,target:90,min_sample:2},admin)).status===200,'admin configures target via API');
  const action=await request(actions,'POST',{month:'2026-01',due_date:'2026-03-01',title:'ทบทวนผลลัพธ์',owner:'ทีมทดสอบ',stage:'plan',detail:'ไม่มีข้อมูลผู้ป่วย'},editor);
  check(action.status===200,`CQI create: ${JSON.stringify(action)}`);
  check((await request(`${actions}/${action.data.id}`,'PATCH',{stage:'check'},editor)).status===200,'CQI update persists');
  check((await request(`${actions}/${action.data.id}`,'PATCH',{stage:'act'},viewer)).status>=400,'viewer CQI write denied');
  check((await request(`${actions}/${action.data.id}`,'DELETE',undefined,admin)).status>=400,'CQI history cannot be deleted by app');
  check((await request(actions,'POST',{month:'2026-99',due_date:'2026-02-30',title:'bad',owner:'bad',stage:'plan'},editor)).status===400,'CQI calendar validation');
  const arch=await request(`${cases}/${id}`,'PATCH',{revision:3,archived:true},admin);check(arch.status===200,'admin archive');
  check(Clinical.kpis([arch.data]).every(k=>k.denominator===0),'archived cases excluded');
  check((await request(`${cases}/${id}`,'PATCH',{revision:4,archived:false},admin)).status===200,'admin restores case');
  const other=await request(cases,'POST',{...sample,eye:'OS'},editor);check(other.status===200,'same HN other eye allowed');
  for(let i=0;i<11;i++)check((await request(cases,'POST',{...sample,hn:`TEST-${i+100}`,surgery_date:'2026-02-01'},editor)).status===200,'additional synthetic case');
  check((await request(`${cases}?perPage=10&page=2`,'GET',undefined,editor)).data.items.length===3,'case pagination');
  check((await request(`${cases}?filter=${encodeURIComponent('hn = "TEST-001"')}`,'GET',undefined,editor)).data.totalItems===2,'case filtering');
  // Role changes and registration retain starter security boundaries.
  for(const role of ['viewer','editor']){
    const token=accounts[role].token;
    check((await request(users,'GET',undefined,token)).data.totalItems===1,`${role} cannot list team`);
    check((await request(`${users}/${accounts[role].record.id}`,'PATCH',{role:'admin'},token)).status>=400,`${role} self-promotion denied`);
  }
  check((await request(users,'GET',undefined,admin)).data.totalItems===3,'admin lists team');
  check((await request(`${users}/${accounts.admin.record.id}`,'PATCH',{active:false},admin)).status>=400,'admin self-deactivation blocked');
  check((await request(`${users}/${accounts.viewer.record.id}`,'PATCH',{verified:true},admin)).status===400,'admin auth-field injection denied');
  check((await request(`${users}/${accounts.viewer.record.id}`,'PATCH',{role:'editor'},admin)).status===200,'admin promotion');
  check((await request(cases,'POST',{...sample,hn:'PROMOTED'},viewer)).status===200,'old token uses current server role');
  check((await request(`${users}/${accounts.viewer.record.id}`,'PATCH',{active:false},admin)).status===200,'admin deactivation');
  check((await request(`${cases}/${id}`,'GET',undefined,viewer)).status>=400,'disabled old token blocked');
  check((await request(cases,'POST',{...sample,hn:'DISABLED'},viewer)).status>=400,'disabled write blocked');
  check((await request('/api/collections/users/auth-with-password','POST',{identity:'viewer@example.test',password})).status>=400,'disabled login blocked');
  await request(`${users}/${accounts.viewer.record.id}`,'PATCH',{active:true,role:'viewer'},admin);
  const reg=await request('/api/starter/register','POST',{name:'New viewer',email:'new@example.test',password,passwordConfirm:password,role:'admin',active:false,verified:true});
  check(reg.status===201 && reg.data.role==='viewer'&&reg.data.active,'registration forces viewer');
  check((await request(users,'POST',{email:'bypass@example.test',password,passwordConfirm:password,role:'admin',active:true})).status>=400,'generic registration blocked');
  check((await request('/api/starter/register','POST',{name:'bot',email:'bot@example.test',password,passwordConfirm:password,website:'spam'})).status===400,'registration honeypot');
  // Calculation regression checks with known denominators and date boundaries.
  const synthetic=[saved.data,{...saved.data,id:'b',va_outcome:'fail',endophthalmitis:'yes'},{...sample,id:'c'}, {...saved.data,id:'d',archived:true}];
  const metrics=Clinical.kpis(synthetic,[{key:'va_outcome',enabled:true,min_sample:2,target:90,direction:'gte'}]);
  check(metrics[0].numerator===1 && metrics[0].denominator===2 && metrics[0].value===50 && metrics[0].missing===1 && metrics[0].status==='fail','VA numerator denominator missing target');
  check(metrics[1].value===50 && metrics[1].denominator===2,'complications exclude unknowns');
  check(Clinical.kpis([saved.data],[{key:'va_outcome',enabled:true,min_sample:2,target:90,direction:'gte'}])[0].status==='insufficient','minimum sample enforced');
  check(Clinical.kpis([saved.data])[0].status==='unconfigured','no hard-coded target');
  const periods=[{surgery_date:'2025-12-31'},{surgery_date:'2026-01-01'},{surgery_date:'2026-03-31'},{surgery_date:'2026-04-01'},{surgery_date:'2026-02-01',archived:true}];
  check(Clinical.period(periods,'2026-03','quarterly').length===2,'quarter boundary');
  check(Clinical.period(periods,'2026-03','ytd').length===2,'YTD boundary');
  check(Clinical.period(periods,'2026-03','monthly').length===1,'month boundary');
  check(Clinical.period(periods,'2026-03','year').length===3,'year boundary');
  check(Clinical.alerts([{id:'x',surgery_date:'2026-01-01',endophthalmitis:'yes'}],'2026-01-31').length===4,'critical and due follow-ups');
  check(Clinical.alerts([{id:'x',surgery_date:'2026-01-01'}],'2026-01-01').length===0,'no premature overdue alert');
  for(const url of ['/','/register.html','/app.js','/api.js','/clinical.js','/styles.css'])check((await fetch(base+url)).status===200,`public asset ${url}`);
  for(const url of ['/pocketbase/pb_data/data.db','/pocketbase/pocketbase.exe','/scripts/setup-pocketbase.ps1','/.git/config'])check((await fetch(base+url)).status===404,`private path blocked ${url}`);
}
