import { createRequire } from 'node:module';
import { isDeepStrictEqual } from 'node:util';
const require=createRequire(import.meta.url);
const Clinical=require('../public/clinical.js');
const Formula=require('../public/kpi-formula.js');
export async function runCataract({request,check,accounts,su,password,base}) {
  const cases='/api/collections/cases/records',users='/api/collections/users/records',audit='/api/collections/audit_logs/records',targets='/api/collections/kpi_targets/records',actions='/api/collections/quality_actions/records';
  const editor=accounts.editor.token,viewer=accounts.viewer.token,admin=accounts.admin.token;
  const sample={hn:'TEST-001',patient_name:'ผู้ป่วยทดสอบเท่านั้น',surgery_date:'2026-01-01',surgeon:'แพทย์สมมติ',procedure:'Phaco + IOL',eye:'OD',diagnosis:'Cataract',pain_score:'0'};
  check((await request(cases,'GET',undefined,admin)).data.totalItems===0,'new database starts empty');
  check(Clinical.kpis([]).every(k=>k.value===null&&k.denominator===0),'empty KPI is N/A');
  check((await request(cases)).data.items.length===0,'guest list empty');
  check((await request(cases,'POST',sample)).status>=400,'guest create blocked');
  check((await request(cases,'POST',sample,viewer)).status>=400,'viewer create blocked');
  const created=await request(cases,'POST',sample,editor);
  check(created.status===200,`editor create case: ${JSON.stringify(created)}`);
  const id=created.data.id;
  check(created.data.created_by===accounts.editor.record.id && created.data.revision===1,'server stamps actor and revision');
  check((await request(`${cases}/${id}`)).status===404,'guest detail blocked');
  for(const [role,token] of [['viewer',viewer],['editor',editor],['admin',admin]]){
    const result=await request(`${cases}/${id}`,'GET',undefined,token);check(result.status===200,`${role} reads case`);
    if(role==='viewer')check(result.data.patient_name==='ปกปิดชื่อผู้ป่วย'&&!result.data.hn.includes('TEST')&&!Object.hasOwn(result.data,'notes'),'viewer API masks identifiers');
  }
  for(const [method,body] of [['PATCH',{surgeon:'changed',revision:1}],['DELETE',undefined]])check((await request(`${cases}/${id}`,method,body,viewer)).status>=400,`viewer ${method} denied`);
  check((await request(`${cases}/${id}`,'DELETE',undefined,editor)).status>=400,'editor delete denied');
  check((await request(`${cases}/${id}`,'DELETE',undefined,admin)).status>=400,'hard delete denied; admin archive instead');
  check((await request(cases,'POST',sample,editor)).status===400,'duplicate HN date eye rejected');
  check((await request(cases,'POST',{...sample,hn:'test-001'},editor)).status===400,'HN case normalization prevents duplicate');
  check((await request(cases,'POST',{...sample,hn:'TAMPER',unknown_field:true},editor)).status===400,'unknown case fields rejected');
  check((await request(`${cases}/${id}`,'PATCH',{revision:1,'created_by+':'forged'},editor)).status===400,'metadata modifiers rejected');
  check((await request('/api/collections/items/records','GET',undefined,admin)).status===403,'legacy item API retired');
  const invalids=[{surgery_date:'2026-02-30'},{surgery_date:'2099-01-01'},{hn:'  '},{hn:'<img>'},{patient_name:'   '},{eye:'X'},{pain_score:'11'},{pain_score:'NaN'},{pain_score:'-1'},{pain_score:'1.5'},{surgery_time:'25:99'},{day1_date:'2026-01-02'},{day1_va:'6/6'},{day1_date:'2025-12-31',day1_va:'6/6'},{day1_date:'2026-01-09',day1_va:'6/6',week1_date:'2026-01-08',week1_va:'6/6'},{va_outcome:'pass'},{endophthalmitis:'maybe'},{created_by:'forged'},{updated_by:'forged'},{archived:true}];
  for(const override of invalids)check((await request(cases,'POST',{...sample,hn:'INVALID',...override},editor)).status>=400,`invalid case rejected ${JSON.stringify(override)}`);
  const full={day1_date:'2026-01-02',day1_va:'6/12',week1_date:'2026-01-08',week1_va:'6/9',month1_date:'2026-02-01',month1_va:'6/6',va_outcome:'pass',endophthalmitis:'no',wound_leak:'no',reoperation:'no',biometry:'pass',refractive:'pass',revision:1};
  const saved=await request(`${cases}/${id}`,'PATCH',full,editor);check(saved.status===200,`follow-up saved: ${JSON.stringify(saved)}`);
  check(saved.data.revision===2 && saved.data.month1_va==='6/6','save persists with incremented revision');
  check((await request(`${cases}/${id}`,'PATCH',{revision:1,notes:'stale'},editor)).status===409,'stale update rejected');
  check((await request(`${cases}/${id}`,'PATCH',{notes:'missing revision'},editor)).status===409,'missing revision rejected');
  check((await request(`${cases}/${id}`,'PATCH',{revision:2,archived:true},editor)).status===403,'editor archive denied');
  const races=await Promise.all([request(`${cases}/${id}`,'PATCH',{revision:2,notes:'race A'},editor),request(`${cases}/${id}`,'PATCH',{revision:2,notes:'race B'},editor)]);
  check(races.filter(r=>r.status===200).length===1 && races.filter(r=>r.status===409).length===1,'concurrent updates have one winner');
  const logs=await request(`${audit}?filter=${encodeURIComponent(`record_id = "${id}"`)}`,'GET',undefined,admin);
  check(logs.data.totalItems===3,`exactly one audit per successful write: ${JSON.stringify(logs)}`);
  check(!JSON.stringify(logs.data).includes(sample.patient_name)&&!JSON.stringify(logs.data).includes(sample.hn),'audit omits patient identifiers');
  check((await request(audit,'GET',undefined,viewer)).data.totalItems===0,'viewer audit denied');
  check((await request(audit,'POST',{entity:'cases',record_id:id,actor:'fake',operation:'create'},admin)).status>=400,'audit injection denied');
  check((await request(`${audit}/${logs.data.items[0].id}`,'DELETE',undefined,admin)).status>=400,'audit deletion denied');
  const defs=await request(targets,'GET',undefined,viewer);check(defs.data.items.length===6 && defs.data.items.every(t=>!t.enabled),'targets seeded as unconfigured metadata');
  const va=defs.data.items.find(t=>t.key==='va_outcome');
  check((await request(`${targets}/${va.id}`,'PATCH',{enabled:true,target:90},editor)).status>=400,'editor cannot configure targets');
  check((await request(`${targets}/${va.id}`,'PATCH',{enabled:true,target:90},viewer)).status>=400,'viewer cannot configure targets');
  check((await request(`${targets}/${va.id}`,'PATCH',{target:-1},admin)).status===400,'negative target rejected');
  check((await request(`${targets}/${va.id}`,'PATCH',{min_sample:1.5},admin)).status===400,'fractional minimum sample rejected');
  check((await request(`${targets}/${va.id}`,'PATCH',{target:101},admin)).status===400,'invalid target rejected');
  check((await request(`${targets}/${va.id}`,'PATCH',{key:'changed'},admin)).status===400,'KPI definition protected');
  check((await request(`${targets}/${va.id}`,'PATCH',{min_sample:0},admin)).status===400,'minimum sample must be positive');
  const targetUpdate=await request(`${targets}/${va.id}`,'PATCH',{enabled:true,target:90,min_sample:2},admin);
  check(targetUpdate.status===200,'admin configures target via API');
  const persistedTarget=await request(`${targets}/${va.id}`,'GET',undefined,admin);
  check(persistedTarget.data.target===90 && persistedTarget.data.min_sample===2 && persistedTarget.data.enabled && persistedTarget.data.updated_by===accounts.admin.record.id,'target settings and server actor persist');
  const targetLog=await request(`${audit}?filter=${encodeURIComponent(`entity = "kpi_targets" && record_id = "${va.id}"`)}`,'GET',undefined,admin);
  check(targetLog.data.totalItems===1 && targetLog.data.items[0].changes.target.before===0 && targetLog.data.items[0].changes.target.after===90 && targetLog.data.items[0].actor===accounts.admin.record.id,'target audit records before after and actor');
  check(Clinical.kpis([saved.data,saved.data],[persistedTarget.data])[0].status==='pass','persisted enabled target drives KPI status');
  const disabledTarget=await request(`${targets}/${va.id}`,'PATCH',{enabled:false},admin);
  check(disabledTarget.status===200 && Clinical.kpis([saved.data,saved.data],[disabledTarget.data])[0].status==='unconfigured','admin disables target without discarding measured outcomes');
  check((await request(`${targets}/${va.id}`,'PATCH',{enabled:true},admin)).status===200,'admin re-enables target');
  check(defs.data.items.every(t=>t.source===t.key),'migration backfills built-in data sources');
  const customBody={label:'VA เป้าหมายทีมทดสอบ',source:'va_outcome',target:95,min_sample:1,enabled:true};
  for (const token of [undefined,viewer,editor]) check((await request(targets,'POST',customBody,token)).status>=400,'only admin creates KPI targets');
  for (const override of [{label:'   '},{source:'patient_name'},{source:''},{target:101},{target:-1},{min_sample:0},{min_sample:1.5},{key:'forged'},{direction:'lte'},{created_by:'forged'},{source:'va_outcome',unknown_field:true}]) {
    check((await request(targets,'POST',{...customBody,...override},admin)).status===400,`invalid new KPI rejected ${JSON.stringify(override)}`);
  }
  const custom=await request(targets,'POST',customBody,admin);
  check(custom.status===200,`admin creates custom KPI: ${JSON.stringify(custom)}`);
  check(custom.data.key.startsWith('custom_')&&custom.data.direction==='gte'&&custom.data.created_by===accounts.admin.record.id,'custom key direction and actor are server-owned');
  check((await request(targets,'POST',customBody,admin)).status===400,'duplicate KPI label rejected');
  const customRead=await request(`${targets}/${custom.data.id}`,'GET',undefined,viewer);
  check(customRead.data.source==='va_outcome'&&customRead.data.target===95,'new KPI persists and viewer can read');
  const customMetric=Clinical.kpis([saved.data], [customRead.data]).find(k=>k.key===custom.data.key);
  check(customMetric.label===customBody.label&&customMetric.value===100&&customMetric.numerator===1&&customMetric.denominator===1&&customMetric.status==='pass','custom KPI calculates using saved source outcomes');
  check(Clinical.kpis([], [customRead.data]).find(k=>k.key===custom.data.key).value===null,'empty custom KPI remains N/A');
  const customLog=await request(`${audit}?filter=${encodeURIComponent(`entity = "kpi_targets" && record_id = "${custom.data.id}"`)}`,'GET',undefined,admin);
  check(customLog.data.totalItems===1&&customLog.data.items[0].operation==='create'&&customLog.data.items[0].changes.source.after==='va_outcome','custom creation has transactional audit');
  for(const body of [{source:'biometry'},{label:'new label'},{direction:'lte'}]) check((await request(`${targets}/${custom.data.id}`,'PATCH',body,admin)).status===400,'saved KPI definition immutable');
  const customDisabled=await request(`${targets}/${custom.data.id}`,'PATCH',{enabled:false,target:96},admin);
  check(customDisabled.status===200&&Clinical.kpis([saved.data],[customDisabled.data]).find(k=>k.key===custom.data.key).status==='unconfigured','custom target can be edited and disabled');
  check((await request(`${targets}/${custom.data.id}`,'DELETE',undefined,admin)).status>=400,'custom KPI uses disable instead of hard delete');
  const complication=await request(targets,'POST',{...customBody,label:'Endophthalmitis เป้าหมายทีม',source:'endophthalmitis',target:0},admin);
  const complicationMetric=Clinical.kpis([saved.data],[complication.data]).find(k=>k.key===complication.data.key);
  check(complication.status===200&&complication.data.direction==='lte'&&complicationMetric.value===0&&complicationMetric.status==='pass','custom complication inherits lower-is-better formula');
  const allCases={match:'all',conditions:[]};
  const followupFormula={mode:'ratio',denominator:allCases,numerator:{match:'all',conditions:[{field:'day1_va',operator:'is_set'},{field:'week1_va',operator:'is_set'},{field:'month1_va',operator:'is_set'}]}};
  const formulaBody={label:'ติดตามครบสามระยะ',source:'custom',formula:followupFormula,direction:'gte',target:90,min_sample:1,enabled:true};
  for(const token of [undefined,viewer,editor])check((await request(targets,'POST',formulaBody,token)).status>=400,'formula creation restricted to admin');
  const formulaTarget=await request(targets,'POST',formulaBody,admin);
  check(formulaTarget.status===200,`admin creates validated custom formula: ${JSON.stringify(formulaTarget)}`);
  const formulaRead=await request(`${targets}/${formulaTarget.data.id}`,'GET',undefined,viewer);
  check(isDeepStrictEqual(formulaRead.data.formula,followupFormula),'custom formula persists unchanged');
  const cohort=[saved.data,{...saved.data,month1_va:'',pain_score:'6'},{...saved.data,day1_va:'',week1_va:'',month1_va:'',pain_score:''},{...saved.data,archived:true,pain_score:'10'}];
  const calculated=Clinical.kpis(cohort,[formulaRead.data]).find(k=>k.key===formulaTarget.data.key);
  check(calculated.numerator===1&&calculated.denominator===3&&Math.abs(calculated.value-100/3)<0.00001&&calculated.status==='fail','custom follow-up numerator denominator excludes archived');
  check(Formula.calculate([],followupFormula).value===null,'zero denominator custom formula is N/A');
  const anyFormula={mode:'ratio',denominator:allCases,numerator:{match:'any',conditions:[{field:'pain_score',operator:'gte',value:5},{field:'month1_va',operator:'is_empty'}]}};
  check(Formula.calculate(cohort,anyFormula).numerator===2,'OR and numeric comparison work without counting overlap twice');
  const subsetFormula={mode:'ratio',denominator:{match:'all',conditions:[{field:'eye',operator:'eq',value:'OS'}]},numerator:allCases};
  check(Formula.calculate(cohort,subsetFormula).denominator===0&&Formula.calculate(cohort,subsetFormula).numerator===0,'numerator cannot count records outside denominator');
  const notEqual={mode:'ratio',denominator:allCases,numerator:{match:'all',conditions:[{field:'pain_score',operator:'ne',value:0}]}};
  check(Formula.calculate(cohort,notEqual).numerator===1,'missing is unknown for not-equal; recorded zero is distinct');
  const averageFormula={mode:'average',denominator:allCases};
  const avgResult=Formula.calculate(cohort,averageFormula);
  check(avgResult.numerator===6&&avgResult.denominator===2&&avgResult.value===3&&avgResult.unit==='คะแนน'&&avgResult.missing===1,'Pain average excludes missing and includes zero');
  const averageTarget=await request(targets,'POST',{...formulaBody,label:'ค่าเฉลี่ย Pain score',formula:averageFormula,direction:'lte',target:3},admin);
  check(averageTarget.status===200&&Clinical.kpis(cohort,[averageTarget.data]).find(k=>k.key===averageTarget.data.key).status==='pass','custom average honors score unit and lower target');
  check((await request(`${targets}/${averageTarget.data.id}`,'PATCH',{target:11},admin)).status===400,'server rejects average target above pain scale');
  check((await request(`${targets}/${formulaTarget.data.id}`,'PATCH',{formula:averageFormula},admin)).status===400,'saved formula cannot be redefined');
  const invalidFormulas=[null,'process.exit()',{}, {...followupFormula,mode:'javascript'}, {...followupFormula,script:'return 1'}, {...followupFormula,denominator:{match:'all',conditions:Array(11).fill({field:'eye',operator:'is_set'})}}, {...followupFormula,numerator:{match:'xor',conditions:[]}}, ...[{field:'patient_name',operator:'eq',value:'x'},{field:'__proto__',operator:'is_set'},{field:'pain_score',operator:'eq',value:'0'},{field:'pain_score',operator:'gt',value:11},{field:'va_outcome',operator:'eq',value:'maybe'},{field:'va_outcome',operator:'is_set',value:'pass'},{field:'month1_va',operator:'eq',value:'6/6'}].map(condition=>({...followupFormula,numerator:{match:'all',conditions:[condition]}}))];
  for(const formula of invalidFormulas)check((await request(targets,'POST',{...formulaBody,label:'Invalid formula',formula},admin)).status===400,`unsafe or invalid formula rejected ${JSON.stringify(formula)}`);
  const formulaAudit=await request(`${audit}?filter=${encodeURIComponent(`entity = "kpi_targets" && record_id = "${formulaTarget.data.id}"`)}`,'GET',undefined,admin);
  check(formulaAudit.data.totalItems===1&&formulaAudit.data.items[0].changes.formula.after.mode==='ratio','audit captures validated formula on create');
  const action=await request(actions,'POST',{month:'2026-01',due_date:'2026-03-01',title:'ทบทวนผลลัพธ์',owner:'ทีมทดสอบ',stage:'plan',detail:'ไม่มีข้อมูลผู้ป่วย'},editor);
  check(action.status===200,`CQI create: ${JSON.stringify(action)}`);
  check((await request(`${actions}/${action.data.id}`,'PATCH',{stage:'check'},editor)).status===200,'CQI update persists');
  check((await request(`${actions}/${action.data.id}`,'PATCH',{stage:'act'},viewer)).status>=400,'viewer CQI write denied');
  check((await request(`${actions}/${action.data.id}`,'DELETE',undefined,admin)).status>=400,'CQI history cannot be deleted by app');
  check((await request(actions,'POST',{month:'2026-99',due_date:'2026-02-30',title:'bad',owner:'bad',stage:'plan'},editor)).status===400,'CQI calendar validation');
  const arch=await request(`${cases}/${id}`,'PATCH',{revision:3,archived:true},admin);check(arch.status===200,'admin archive');
  check(Clinical.kpis([arch.data]).every(k=>k.denominator===0),'archived cases excluded');
  check((await request(`${cases}/${id}`,'PATCH',{revision:4,archived:false},admin)).status===200,'admin restores case');
  const other=await request(cases,'POST',{...sample,eye:'OS'},editor);check(other.status===200,'same HN other eye allowed');
  for(let i=0;i<11;i++)check((await request(cases,'POST',{...sample,hn:`TEST-${i+100}`,surgery_date:'2026-02-01'},editor)).status===200,'additional synthetic case');
  check((await request(`${cases}?perPage=10&page=2`,'GET',undefined,editor)).data.items.length===3,'case pagination');
  check((await request(`${cases}?filter=${encodeURIComponent('hn = "TEST-001"')}`,'GET',undefined,editor)).data.totalItems===2,'case filtering');
  // Role changes and registration retain starter security boundaries.
  for(const role of ['viewer','editor']){
    const token=accounts[role].token;
    check((await request(users,'GET',undefined,token)).data.totalItems===1,`${role} cannot list team`);
    check((await request(`${users}/${accounts[role].record.id}`,'PATCH',{role:'admin'},token)).status>=400,`${role} self-promotion denied`);
  }
  check((await request(users,'GET',undefined,admin)).data.totalItems===3,'admin lists team');
  check((await request(`${users}/${accounts.admin.record.id}`,'PATCH',{active:false},admin)).status>=400,'admin self-deactivation blocked');
  check((await request(`${users}/${accounts.viewer.record.id}`,'PATCH',{verified:true},admin)).status===400,'admin auth-field injection denied');
  check((await request(`${users}/${accounts.viewer.record.id}`,'PATCH',{role:'editor'},admin)).status===200,'admin promotion');
  check((await request(cases,'POST',{...sample,hn:'PROMOTED'},viewer)).status===200,'old token uses current server role');
  check((await request(`${users}/${accounts.viewer.record.id}`,'PATCH',{active:false},admin)).status===200,'admin deactivation');
  check((await request(`${cases}/${id}`,'GET',undefined,viewer)).status>=400,'disabled old token blocked');
  check((await request(cases,'POST',{...sample,hn:'DISABLED'},viewer)).status>=400,'disabled write blocked');
  check((await request('/api/collections/users/auth-with-password','POST',{identity:'viewer@example.test',password})).status>=400,'disabled login blocked');
  await request(`${users}/${accounts.viewer.record.id}`,'PATCH',{active:true,role:'viewer'},admin);
  const reg=await request('/api/starter/register','POST',{name:'New viewer',email:'new@example.test',password,passwordConfirm:password,role:'admin',active:false,verified:true});
  check(reg.status===201 && reg.data.role==='viewer'&&reg.data.active,'registration forces viewer');
  check((await request(users,'POST',{email:'bypass@example.test',password,passwordConfirm:password,role:'admin',active:true})).status>=400,'generic registration blocked');
  check((await request('/api/starter/register','POST',{name:'bot',email:'bot@example.test',password,passwordConfirm:password,website:'spam'})).status===400,'registration honeypot');
  // Calculation regression checks with known denominators and date boundaries.
  const synthetic=[saved.data,{...saved.data,id:'b',va_outcome:'fail',endophthalmitis:'yes'},{...sample,id:'c'}, {...saved.data,id:'d',archived:true}];
  const metrics=Clinical.kpis(synthetic,[{key:'va_outcome',enabled:true,min_sample:2,target:90,direction:'gte'}]);
  check(metrics[0].numerator===1 && metrics[0].denominator===2 && metrics[0].value===50 && metrics[0].missing===1 && metrics[0].status==='fail','VA numerator denominator missing target');
  check(metrics[1].value===50 && metrics[1].denominator===2,'complications exclude unknowns');
  check(Clinical.kpis([saved.data],[{key:'va_outcome',enabled:true,min_sample:2,target:90,direction:'gte'}])[0].status==='insufficient','minimum sample enforced');
  check(Clinical.kpis([saved.data])[0].status==='unconfigured','no hard-coded target');
  const periods=[{surgery_date:'2025-12-31'},{surgery_date:'2026-01-01'},{surgery_date:'2026-03-31'},{surgery_date:'2026-04-01'},{surgery_date:'2026-02-01',archived:true}];
  check(Clinical.period(periods,'2026-03','quarterly').length===2,'quarter boundary');
  check(Clinical.period(periods,'2026-03','ytd').length===2,'YTD boundary');
  check(Clinical.period(periods,'2026-03','monthly').length===1,'month boundary');
  check(Clinical.period(periods,'2026-03','year').length===3,'year boundary');
  check(Clinical.alerts([{id:'x',surgery_date:'2026-01-01',endophthalmitis:'yes'}],'2026-01-31').length===4,'critical and due follow-ups');
  check(Clinical.alerts([{id:'x',surgery_date:'2026-01-01'}],'2026-01-01').length===0,'no premature overdue alert');
  for(const url of ['/','/register.html','/app.js','/api.js','/clinical.js','/styles.css'])check((await fetch(base+url)).status===200,`public asset ${url}`);
  for(const url of ['/pocketbase/pb_data/data.db','/pocketbase/pocketbase.exe','/scripts/setup-pocketbase.ps1','/.git/config'])check((await fetch(base+url)).status===404,`private path blocked ${url}`);
  check(Clinical.kpis(synthetic,defs.data.items).length===5&&!Clinical.kpis(synthetic,defs.data.items).some(k=>k.key==='refractive'),'retired built-in refractive does not reappear as a custom KPI');
  check(Clinical.kpis(synthetic,[{key:'custom_legacy_refractive',source:'refractive',label:'Existing custom',enabled:false,min_sample:1}]).some(k=>k.key==='custom_legacy_refractive'&&k.value!==null),'existing explicitly configured custom source keeps its calculation');
  for(const [index,lens_type] of Clinical.lensTypes.entries()){
    const lensCase=await request(cases,'POST',{...sample,hn:`LENS-${index}`,lens_type,implant:'Test IOL / +21.0D',surgery_time:index===0?'00:00':'23:59'},editor);
    check(lensCase.status===200&&lensCase.data.lens_type===lens_type&&lensCase.data.implant==='Test IOL / +21.0D','approved lens option and implant persist');
    check((await request(`${cases}/${lensCase.data.id}`,'PATCH',{revision:lensCase.data.revision,lens_type:'Unknown lens'},editor)).status===400,'invalid changed lens rejected');
  }
  for(const value of ['Unknown lens','monofocal iol','   '])check((await request(cases,'POST',{...sample,hn:'BAD-LENS',lens_type:value},editor)).status===400,'new case rejects unsupported lens type');
  for(const value of ['24:00','12:60','12','12:','-1:30','12:30:00'])check((await request(cases,'POST',{...sample,hn:'BAD-TIME',surgery_time:value},editor)).status===400,'invalid surgery time rejected');
}
